### ISSUE TITLE
Document behavior of enum when casted to an integer

### ISSUE THREAD

**Issue by jmi2k** [rust-lang-nursery/reference#10]
Consider the following example:

```rust
enum Foo {
    A,
    B,
    C
}

fn main() {
    println!("{}", Foo::A as usize);
    println!("{}", Foo::B as usize);
    println!("{}", Foo::C as usize);
}
```

The current behavior is that Foo members get casted to an increasing sequence starting from 0. Although that seems to be the most reasonable default, it should be documented to make clear that it won't be changed in the future.

**Comment by frewsxcv** [comment]
Somewhat related, the book has a section on casting semantics that maybe should be copied/moved into the reference:

https://doc.rust-lang.org/book/casting-between-types.html

Though, it doesn't look like there's much there on enum casting

**Comment by steveklabnik** [comment]
@aturon so, here's an interesting wrinkle. We were talking about getting the lang team and the docs team together to tackle issues like this one, but given this is in the nursery and not rust-lang, I can't cc @rust-lang/lang 😦

**Comment by aturon** [comment]
@steveklabnik Whelp! I guess there are basically two options here:

- Add in the teams to the nursery, which would probably be useful across the board.
- Move the reference to rust-lang.

I'm not sure what the status of the latter is. Was there some particular "graduation" point we had in mind?

**Comment by steveklabnik** [comment]
>  Was there some particular "graduation" point we had in mind?

I said "hey @alexcrichton ! Should this go in the nursery or rust-lang. I don't care." He shugged. So we asked @brson. He said "Eh given its level of polish let's put it in the nursery", to which alex and I said 🆒 .

So, it was basically a coinflip, and we didn't have any particular criteria set up.

**Comment by aturon** [comment]
@steveklabnik 

Heh, alright! Let's keep this in mind when we set up the docs + lang team discussion soon.

**Comment by alercah** [comment]
This is now fixed: https://doc.rust-lang.org/nightly/reference/items/enumerations.html

**Comment by frewsxcv** [comment]
yep! looks like @Havvy took care of this in https://github.com/rust-lang-nursery/reference/pull/156 🎉
