### ISSUE TITLE
expressions precedence

### ISSUE THREAD

**Issue by montrivo** [rust-lang-nursery/reference#107]
Hello,

I don't find any documentation about rust expression precedence rules in the book and reference. Could someone point me to it if it exists? If not, should it be added to the reference? Related forum [post](https://users.rust-lang.org/t/precedence-in-rust/1385) and rust issue [#21799](https://github.com/rust-lang/rust/issues/21799) and [#44288](https://github.com/rust-lang/rust/issues/44288).

Explanation:
In cases where expression parsing is ambiguous, there must be some expression precedence rules. For operator expressions it is documented in the reference as _operator precedence_. But for general expressions it is unclear, in ambiguous cases, which expression type takes precedence over the other. Two examples: `0..10.some_method()` (range expr vs method call expr), `&some_struct.some_method()` (operator expr vs method call expr).

Thank you

**Comment by QuietMisdreavus** [comment]
Since `..` and `...` (which needs to be converted to `..=` now) are already in the operator precedence listing, it would probably work to add `.` (field/method access), `&` (referencing), and `[]` (indexing) to the listing to solve this.

**Comment by pornel** [comment]
I'll second the request. Auto-deref magic makes precedence even less obvious, e.g. `foo.bar` doesn't work for `*const _`, because it needs to be `(*foo).bar` (and not `*foo.bar`).

Also syntex_syntax does not insert parenthesis when printing AST, so AST nodes with incorrect precedence generate invalid code :(

**Comment by brauliobz** [comment]
I didn't test much, but from what I could gather, the sequence is basically the following:

* expressions such as `break`, `return`, closures, etc., have the same and lowest precedence. They accept an "open" expression after them. `|| a + b` is `|| (a + b)`, not `(|| a) + b`.
* followed by operator expressions (those [documented on the reference](https://doc.rust-lang.org/reference/expressions.html#operator-precedence))
* followed by `.field`, `.tupleField`, `.methodCal()`, `fnCallOrEnumVariant()`, `e[arrayIndex]`, which have the same precedence and are interpreted from left to right as they appear.
* and precedence doesn't matter to expressions that enclose all of their subexpressions. For example tuples `(e,e,e)`, arrays `[e,e,e]` and `[e;3]`, parenthesized expressions`(e)`, `if`, `if let`, `for`, `while`, etc..

**Comment by brauliobz** [comment]
[Some tests I've made](https://play.rust-lang.org/?gist=ba6b24c9f1e48710455ade47d4bb418c&version=stable)
