### ISSUE TITLE
Add Best-Effort Warning at top of page

### ISSUE THREAD

**Issue by Havvy** [rust-lang-nursery/reference#118]
Add a warning to the top of the page detailing that the reference is currently at a best-effort stage, like the warning for the second edition Rust-book (see image).

![Text from Rust book 2nd edition with warning class](https://i.imgur.com/z9Da6TF.png)

The text of this warning should contain the following or similar text, but with proper linking:

"For now, the Rust reference is a best-effort document. We strive for validity and completeness, but are not yet there. At some point in the future, the docs and lang team will work together to figure out how best to do this. Until then, this document is a best-effort attempt. If you find something wrong or missing, file an issue or send in a pull request."

**Comment by steveklabnik** [comment]
This is implemented here: https://github.com/rust-lang/book/tree/master/second-edition/theme

basically, we'd create a theme directory and then modify that index.hbs
