### ISSUE TITLE
Remove Unstable Documentation

### ISSUE THREAD

**Issue by Havvy** [rust-lang-nursery/reference#119]
As per #111, we don't yet have a story on whether we want to document unstable aspects of Rust, and if we do, how do we want to do so?

**Comment by brauliobz** [comment]
The [Unstable Book](https://doc.rust-lang.org/unstable-book/) seems to be the correct place to put unstable things. It is also in a better format for this kind of thing, in my opinion.

**Comment by Havvy** [comment]
I concur with @brauliobz that unstable features should be documented primarily in the *Unstable Book*. This would make the reference primarily about stable features in the language and we'd merge in what's in the *Unstable Book* when a feature is stabilized. We would then add information to the introduction stating it's only documenting what is available in stable rust.

Right now there are unstable features documented in the reference. There's even a PR (#111) to remove one instance of it. I want to merge it, but also have the commented out portion on how to change when it stabilizes be located in the *Unstable Book*.

Do we need an RFC to make this policy change? Or would consensus in a docs meeting be good enough? Or something else?

**Comment by QuietMisdreavus** [comment]
In principle i agree - now that the Unstable Book exists, things that are unstable belong there, by definition. I don't recall whether official policy was made on moving existing docs on unstable things to the Unstable Book (standard library documentation notwithstanding). I've added this to the agenda for the next docs team meeting so we can double-check this.

**Comment by steveklabnik** [comment]
We did do that with the Book v1...

**Comment by steveklabnik** [comment]
Talked about it at the docs team. We're basically all in agreement: only stable stuff should go in the reference. Moving the unstable stuff to the unstable book is good. Let's keep this issue open to track that, as well as actually stating this somewhere in the text.

**Comment by Havvy** [comment]
Yay. I'll update the issue when I get home and write a PR for the front page.
