### ISSUE TITLE
document constant expressions

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang-nursery/reference#18]
Moved from https://github.com/rust-lang/rust/issues/5551

-----------------------

The section on "static items" (formerly entitled "constants") refers to some class of "constant expressions", but we have not defined what these are.

(I think catamorphism has noted this via comments in a few issues I have seen, but I have not seen an actual Issue for this topic; so I am promoting it to a full fledged issue.)

In particular, if we need a subgrammar, or some other sort of static analysis to classify the constant expressions correctly, then we should document it.

**Comment by matthewjasper** [comment]
Do #13 (which documents constant expressions) and #70 (which adds a link from the constants section) resolve this?

**Comment by Havvy** [comment]
I think #13 and #70 resolve this, so closing as fixed.
