### ISSUE TITLE
overflows when do right shift operation in mut

### ISSUE THREAD

**Issue by maomaoguan** [rust-lang-nursery/reference#181]
I am a professional working at Alibaba. Just found an issue (possibly is, to be confirmed). Hope this can be addressed in next version. details are described as below:

operation of right shift on zero will overflow when this operation is made on a mut, will not when it is applied on const. doesn't make sense since there isn't any assignments operations being made on mut variable. 

issue can be reproduced trying code snipped below on version rustc 1.22.1 (05e2e1c41 2017-11-22).

 let mut merged : i8 = 0;
  let mut i = 16;
// no crash
println!("no-crash-shift {}", (0 >> 16)); 
  // crash here
  println!("crash-shift {}", (merged >> i));

**Comment by QuietMisdreavus** [comment]
This may have been better suited for https://github.com/rust-lang/rust instead - this repo is just for the documentation in the language reference.

Regardless, this is actually intended behavior. [Arithmetic operations panic on overflow](https://doc.rust-lang.org/reference/expressions/operator-expr.html#overflow), to attempt to force people to understand what they want to happen when that happens. This includes the left and right shift operations, when you're asking to shift a number of bits more than what the type has. You're asking to shift an 8-bit number by 16 bits - that's what's causing the panic.

To remedy this, there are several options available on the `i8` type: [`checked_shr`], [`wrapping_shr`], [`overflowing_shr`], and [`rotate_right`], each doing something slightly different (and with different return values).

[`checked_shr`]: https://doc.rust-lang.org/std/primitive.i8.html#method.checked_shr
[`wrapping_shr`]: https://doc.rust-lang.org/std/primitive.i8.html#method.wrapping_shr
[`overflowing_shr`]: https://doc.rust-lang.org/std/primitive.i8.html#method.overflowing_shr
[`rotate_right`]: https://doc.rust-lang.org/std/primitive.i8.html#method.rotate_right

**Comment by maomaoguan** [comment]
that one makes sense. thanks for the explanation
