### ISSUE TITLE
Document 43291

### ISSUE THREAD

**Issue by Havvy** [rust-lang-nursery/reference#189]
There's yet another footgun in the language right now, as per https://github.com/rust-lang/rust/issues/43291 and so it should be documented if nobody plans on fixing it soon.

**Comment by mrhota** [comment]
@Havvy  it's fixed as of 10 days ago

**Comment by nodakai** [comment]
I don't think the semantics of `int_val as *_ T` is clearly documented anywhere, and ironically the "fix" rust-lang/rust#47147 had no impact on the reference!

* https://doc.rust-lang.org/nightly/reference/expressions/operator-expr.html#type-cast-expressions

> Integer type | *V where V: Sized | Address to pointer cast

What is the "address to pointer cast" !? Perhaps the original author of this paragraph had LLVM's (zero-extending) `inttoptr` operation in mind...

* https://llvm.org/docs/LangRef.html#inttoptr-to-instruction

Anyways can we repurpose this ticket for the accurate documentation of casts involving pointers?

**Comment by matthewjasper** [comment]
Pointer casts are tracked at #66.
