### ISSUE TITLE
 Document bool cast semantics

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang-nursery/reference#20]
Moved from https://github.com/rust-lang/rust/issues/34729

--------------------------------------

After a short debate on the IRC over whether true as i32 is guaranteed to be 1, and false as i32 is guaranteed to be 0, I think that the semantics section on casts should explicitly describe what a bool as integer_type cast does.

**Comment by est31** [comment]
As I've said in https://github.com/rust-lang/rust/issues/34729, it is [defined indirectly](https://doc.rust-lang.org/reference.html#behavior-considered-undefined) in the reference, but not directly (yet).

**Comment by frewsxcv** [comment]
Related to casting: https://github.com/rust-lang-nursery/reference/issues/10

**Comment by matthewjasper** [comment]
#13 closes this (unless the behavior is not in fact guaranteed to be true to 1, false to 0).

**Comment by lukaramu** [comment]
Triage: [looks like this is fixed now](https://doc.rust-lang.org/nightly/reference/expressions.html#semantics)

**Comment by frewsxcv** [comment]
Agreed, thanks for pointing it out!
