### ISSUE TITLE
Document RFC 2128

### ISSUE THREAD

**Issue by alercah** [rust-lang-nursery/reference#225]
[RFC 2128](https://github.com/rust-lang/rfcs/tree/master/text/2128-use-nested-groups.md) (use-nested-groups) is near stabilization; docs are already present in the [unstable book](https://doc.rust-lang.org/nightly/unstable-book/language-features/use-nested-groups.html).

**Comment by alercah** [comment]
@pietroalbini volunteered to take this on.

**Comment by pietroalbini** [comment]
Sure, I'll send a PR in the next few days.
