### ISSUE TITLE
Documentation for auto traits makes incorrect claims about Sync.

### ISSUE THREAD

**Issue by alercah** [rust-lang-nursery/reference#257]
https://doc.rust-lang.org/nightly/reference/special-types-and-traits.html#auto-traits

This page claims that if `T` is `Sync`, then so is `&mut T`. This is false, however. I believe that it's false for `RefUnwind` as well.

**Comment by matthewjasper** [comment]
I think the documentation is correct: this compiles

```rust
pub fn use_sync<T: Sync>() {
    use_sync::<&mut T>();
}
```

**Comment by alercah** [comment]
Err, right. The issue still exists with `RefUnwind`, however.

**Comment by alercah** [comment]
Additionally, `&T` is not necessarily `Send` if `T` is `Send`; `&T` is `Send` if and only if `T` is `Sync`.
