### ISSUE TITLE
'Compiler Features' section overlaps with Unstable Book

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang-nursery/reference#27]
[The Unstable Book](https://doc.rust-lang.org/nightly/unstable-book/) is going to document all the currently unstable features. Is it worth keeping the content in this section around? https://doc.rust-lang.org/nightly/reference/attributes.html#compiler-features

Relevant issue: https://github.com/rust-lang-nursery/reference/issues/9

**Comment by steveklabnik** [comment]
I don't think it is. There was nowhere else to put this before, but now there is.
