### ISSUE TITLE
`'_` lifetime (RFC 2115)

### ISSUE THREAD

**Issue by matthewjasper** [rust-lang-nursery/reference#278]
This is stabilized in 1.26.

- [x] Add `'_` to _Lifetime_ grammar
- [x] Explain how it works in lifetime-elision.md
- [x] Use it in examples

**Comment by Havvy** [comment]
Is this complete? Or are we keeping open for if it becomes required in the 2018 edition as well?

**Comment by matthewjasper** [comment]
I've check for any other places where `'_` could be used and I think that there aren't any.
