### ISSUE TITLE
Macro documentation is sorely lacking

### ISSUE THREAD

**Issue by alercah** [rust-lang-nursery/reference#294]
Our macro documentation currently has slim documentation on macros by example, and nearly no documentation on procedural macros. Additionally, there is almost no documentation about macro invocation, such as where they are allowed or not allowed. Macros are a language feature like any other, and should be fully documented.

The following RFCs should be fully documented, at least:

[RFC 0085](https://github.com/rust-lang/rfcs/blob/master/text/0085-pattern-macros.md)
[RFC 0378](https://github.com/rust-lang/rfcs/blob/master/text/0378-expr-macros.md)
[RFC 0453](https://github.com/rust-lang/rfcs/blob/master/text/0453-macro-reform.md)
[RFC 0550](https://github.com/rust-lang/rfcs/blob/master/text/0550-macro-future-proofing.md)
[RFC 0873](https://github.com/rust-lang/rfcs/blob/master/text/0873-type-macros.md)
[RFC 1681](https://github.com/rust-lang/rfcs/blob/master/text/1681-macros-1.1.md)

**Comment by steveklabnik** [comment]
For procedural macros, I have a tiny crate here:

https://github.com/sparkles-web/sparkles/blob/master/example-app/src/main.rs

https://github.com/sparkles-web/sparkles/blob/master/sparkles-macros/src/lib.rs

**Comment by ehuss** [comment]
Macros-by-example are now significantly improved via #511.

Macro invocation sites, grammar, and more was added in #458.

Proc-macros were done in #412.

I believe the listed RFCs are covered now, so closing this issue. There's likely more that can be added about macros, but new issues should probably be opened for specific shortcomings.
