### ISSUE TITLE
Document type grammar

### ISSUE THREAD

**Issue by alercah** [rust-lang-nursery/reference#299]
Currently the reference does not document the grammar for types. This is relevant for precedence of operators, e.g. how `&(Foo + Sized)` must be written rather than `&Foo + Sized`.

A type grammar is present in [RFC 0438](https://github.com/rust-lang/rfcs/blob/master/text/0438-precedence-of-plus.md), but I don't know if it's up to date.

**Comment by ehuss** [comment]
I think this can be closed now that #433 is done.  Hopefully it describes the `+` operator ambiguity sufficiently.
