### ISSUE TITLE
Lack of syntax highighting

### ISSUE THREAD

**Issue by matthewjasper** [rust-lang-nursery/reference#3]
Many code blocks aren't correctly started with ```rust so don't have syntax highlighting or lines starting with # removed:
![broken highlighting](https://cloud.githubusercontent.com/assets/20113453/23582353/3089466e-0120-11e7-9f2b-91b10d7fdbdb.png)

**Comment by steveklabnik** [comment]
Yup, we've got some work to do here. Patches very welcome!
