### ISSUE TITLE
Document the doc attribute

### ISSUE THREAD

**Issue by alercah** [rust-lang-nursery/reference#305]
Currently we just refer to the book for the `doc` attribute, we should fully document it.

**Comment by Havvy** [comment]
cc @QuietMisdreavus 

As I remember, it was decided to specifically not document it in the reference in favor of having it only in the rustdoc book which is also reference material.

**Comment by QuietMisdreavus** [comment]
Yeah, the *language* doesn't care about the doc attribute per se, it's only what rustdoc does with it that makes it interesting. I believe the idea was that we would describe it in detail in the Rustdoc Book, and point the reference to that for anything more than "doc comments desugar to doc attributes".

**Comment by Havvy** [comment]
Can we close this as per the previous comment's statement?

**Comment by Havvy** [comment]
Closing as per previous comment.
