### ISSUE TITLE
nightly link is rendering oddly

### ISSUE THREAD

**Issue by ehuss** [rust-lang-nursery/reference#314]
The version at https://doc.rust-lang.org/nightly/reference/ is rendering with an overlap with the content at the top of the page:

![image](https://user-images.githubusercontent.com/43198/38469817-97233658-3b0f-11e8-8324-356dc1408a26.png)

I'm not sure what's wrong, because I don't see this on my local build.
I've tried a few different browsers, and they all behave the same.

**Comment by ehuss** [comment]
It looks like this is fixed in rust-lang-nursery/mdBook#648.  It removes some absolute positioning that was causing problems.    

Is this correct?: That link is updated by the rust nightly build, and this will get fixed once a new release of mdBook is made and the rust Cargo.lock gets updated for mdBook?  It looks like mdBook was bumped a few days ago to version 0.1.5 from 0.1.2.

**Comment by steveklabnik** [comment]
This should be fixed with the next nightly.
