### ISSUE TITLE
Disclaimer at top of reference has broken layout with latest mdbook

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang-nursery/reference#317]
https://doc.rust-lang.org/nightly/reference/introduction.html

<img width="1037" alt="screen shot 2018-04-16 at 1 58 16 pm" src="https://user-images.githubusercontent.com/416575/38790779-5f926388-417e-11e8-9613-de3296e935f8.png">

**Comment by frewsxcv** [comment]
code:

- https://github.com/rust-lang-nursery/reference/blob/e6a5d5d10aa2fde0baed7b29bf672bd9f3af8962/src/theme/header.hbs
- https://github.com/rust-lang-nursery/reference/blob/aeeb04d5456ffa9394c04987483872ac9de6481a/src/theme/reference.css#L8-L46

**Comment by ehuss** [comment]
This is fixed in mdbook, but a new release has not yet been made.  See #314.

**Comment by steveklabnik** [comment]
duplicate of https://github.com/rust-lang-nursery/reference/issues/314
