### ISSUE TITLE
pure keyword removed

### ISSUE THREAD

**Issue by padget** [rust-lang-nursery/reference#370]
the keyword 'pure' was recently removed from rust. 
In this page https://doc.rust-lang.org/reference/keywords.html, 'pure' is present.

**Comment by QuietMisdreavus** [comment]
That keyword has been removed from the reference, but the update has not reached the stable docs. On the nightly version - https://doc.rust-lang.org/nightly/reference/keywords.html - the `pure` keyword is no longer present.

**Comment by padget** [comment]
So I close this issue.
