### ISSUE TITLE
`impl !<TraitName> for <Type> { .. }` should be documented

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang-nursery/reference#371]
As far as I know, this isn't documented and it seems like something worth calling out

Relevant: https://github.com/rust-lang/rust/issues/51129

**Comment by alercah** [comment]
`impl !Trait` isn't stable. It appears in the docs and is mentioned in the section on auto traits, but otherwise shouldn't be added until and unless it proceeds to stabilization.

**Comment by frewsxcv** [comment]
I know it's not stable to implement, but someone who is using stable Rust still needs to have an understanding of how it works, right?

**Comment by alercah** [comment]
It's covered in the section on [auto traits](https://doc.rust-lang.org/nightly/reference/special-types-and-traits.html?highlight=auto,tra#auto-traits)
