### ISSUE TITLE
Broken link in enumerations.md

### ISSUE THREAD

**Issue by JoshBrudnak** [rust-lang-nursery/reference#402]
In the [enumerations.md](https://github.com/rust-lang-nursery/reference/blob/master/src/items/enumerations.md) file the link to enumerated types is broken.

Currently the link is to https://github.com/rust-lang-nursery/reference/blob/master/src/items/types.html#enumerated-types but that file has been moved to https://github.com/rust-lang-nursery/reference/blob/master/src/types.md#enumerated-types.

**Comment by phansch** [comment]
It looks like this has been fixed already: https://doc.rust-lang.org/nightly/reference/items/enumerations.html

**Comment by Havvy** [comment]
Confirmed.
