### ISSUE TITLE
Refiled "Rename UFCS to accurately reflect its functionality"

### ISSUE THREAD

**Issue by Centril** [rust-lang-nursery/reference#449]
Refiling https://github.com/rust-lang/rfcs/issues/1140

> `UFCS` (_"Unified Function Call Syntax"_ #132) ended up being merely an "unified syntax", but not specific to functions and less so to calls.
> 
> It also doesn't allow calling free functions like methods, like D's UFCS does.
> 
> To avoid turning our feature into another `RAII-AA` (_"Acronym Accident"_), I propose renaming it to `AILS` (_"Associated Item Lookup Syntax"_).

**Comment by Havvy** [comment]
This was already done. See https://doc.rust-lang.org/nightly/reference/expressions/call-expr.html#disambiguating-function-calls

**Comment by Centril** [comment]
Cool; Closing then.

**Comment by eddyb** [comment]
FWIW I am lately partial to "type-qualified" (`<T>::`) and "trait-qualified" `(<T as Trait>::`) *without* using "fully-qualified" *at all*. cc @nikomatsakis
