### ISSUE TITLE
More complete example for a derive mode macro

### ISSUE THREAD

**Issue by levkk** [rust-lang-nursery/reference#461]
Hi!

I'm having trouble learning how to implement my own [derive mode macro](https://doc.rust-lang.org/reference/procedural-macros.html#derive-mode-macros) with the given example. Would it be possible to provide a full example on how to implement a macro that accesses the fields in a struct and does some simple operation? For example, in the Serde crate, the `#[derive(Serialize)` macro must (I think) access each individual field and produce a String representation of each.

Specifically, it would be nice to see how the `TokenStream` trait is used.

Thanks!

**Comment by alercah** [comment]
While it's true that it would be good to have an example of a more sophisticated use of procedural macros, anything more complicated like that probably would rely on a library like [syn](https://crates.io/crates/syn), which brings it outside the scope of the reference. This would be valuable content, but this is not the place for it.
