### ISSUE TITLE
`if let` semantically equivalence to `if` is wrong w.r.t. scope

### ISSUE THREAD

**Issue by Havvy** [rust-lang-nursery/reference#47]
The equivalence is wrong because the scope of the expression in the predicate has to live as long as the consequent because of the ability to `ref` in the pattern.

Or something like that.

**Comment by eddyb** [comment]
For the record:
```rust
if let a = b { c } /* optional else */ d
```
Desugars to:
```rust
match b {
    a => c,
    _ => d
}
```
So `b` is in scope, *not only* for `c` but also for `d` (except for what `a` moves out).

**Comment by alercah** [comment]
There doesn't seem to be text in the current version which describes this equivalence, unless I'm looking in the wrong place.
