### ISSUE TITLE
Is UB in FFI also UB in Rust?

### ISSUE THREAD

**Issue by kpp** [rust-lang-nursery/reference#485]
Link to ref: https://doc.rust-lang.org/reference/behavior-considered-undefined.html

> Warning: The following list is not exhaustive. There is no formal model of Rust's semantics for what is and is not allowed in unsafe code, so there may be more behavior considered unsafe.

My question is:
Does undefined behavior inside an extern FFI function also cause an UB in Rust?

------

There is an item inside of the list of **Behavior considered undefined**:
> * Invoking undefined behavior via compiler intrinsics:

I consider adding one more item:
> * Invoking undefined behavior via FFI:

**Comment by Centril** [comment]
cc @rkruppe @RalfJung @ubsan

**Comment by kpp** [comment]
@ubsan is this the answer to the first or the second question (or both)?

**Comment by ubsan** [comment]
@kpp the second question - if you have UB in C code that you call, then your program has UB. It's not Rust UB, because that doesn't make a lot of sense.

**Comment by RalfJung** [comment]
> Does undefined behavior inside an extern FFI function also cause an UB in Rust?

It causes UB in your *entire program*. The UB originates from the C part, so it's not "UB in Rust", but that doesn't help at all -- if you link together pieces written in different languages with a conventional linker, UB in any component "bleeds" into all the other components.

**Comment by kpp** [comment]
Alright. What about question `2.b` from my [comment](https://github.com/rust-lang-nursery/reference/issues/485#issuecomment-449878853)?

**Comment by RalfJung** [comment]
@kpp every piece of code is evaluated following the rules of the language it is written in.  Integer overflow is not UB in Rust, so it is also not UB in Rust when that code is called from C.

**Comment by kpp** [comment]
> So that whole program does not have UB.

Awesome! Thanks!

What about the main question:

I consider adding one more item into the list of **Behavior considered undefined**:
> * Invoking undefined behavior via FFI:

**Comment by RalfJung** [comment]
I don't know if that's helpful. It's not UB in Rust to have UB in C, it's just UB in your program.  But FFI should probably appear in that list somewhere.
