### ISSUE TITLE
Language in constant evaluation section is unclear

### ISSUE THREAD

**Issue by chriskrycho** [rust-lang-nursery/reference#497]
This text from [**Constant Evaluation**: Constant Expressions][ce-ce] is a bit murky:

[ce-ce]: https://doc.rust-lang.org/reference/const_eval.html#constant-expressions

> Certain types of expressions can be evaluated at compile time. These are called constant expressions and are required in const contexts. In other places, such as in [`let` statements], constant expressions may be evaluated at compile time. If errors, such as out of bounds [array indexing] or [overflow] occurs, then it is a compiler error if the value must be evaluated at compile time, otherwise it is just a warning, but the code will most likely panic when run.
> 
> [`let` statements]: 
https://doc.rust-lang.org/reference/statements.html#let-statements
> [array indexing]: 
https://doc.rust-lang.org/reference/expressions/array-expr.html#array-and-slice-indexing-expressions
> [overflow]: 
https://doc.rust-lang.org/reference/expressions/operator-expr.html#overflow

Suggested rephrasing:

> Certain types of expressions, called constant expressions, can be evaluated at compile time. In [const contexts], these are the only allowed expressions, and are always evaluated at compile time. In other places, such as in [`let` statements], constant expressions are allowed but not required, and *may* be evaluated at compile time. Errors such as out of bounds [array indexing] or [overflow] are compiler errors if the value must be evaluated at compile time (i.e. in const contexts); otherwise they are just warnings, but the code will most likely panic when run.
>
> [const contexts]: https://doc.rust-lang.org/reference/const_eval.html#const-context
> [`let` statements]: 
https://doc.rust-lang.org/reference/statements.html#let-statements
> [array indexing]: 
https://doc.rust-lang.org/reference/expressions/array-expr.html#array-and-slice-indexing-expressions
> [overflow]: 
https://doc.rust-lang.org/reference/expressions/operator-expr.html#overflow

Happy to submit a PR to that effect or similar!

**Comment by Centril** [comment]
The rewording seems mostly better; happy to tweak it together in a PR if you want to submit one.

**Comment by chriskrycho** [comment]
Cool; I'll try to get one open tomorrow. Very happy to tweak it – I was literally just saying "I think this is what actually makes sense" and figured it was only mostly right at best! 😆
