### ISSUE TITLE
Replace NUMBER SIGN comments with //

### ISSUE THREAD

**Issue by behnam** [rust-lang-nursery/reference#52]
In many locations in the Reference document, I see these lines:
```
# fn main() {}
```

Like here:
https://doc.rust-lang.org/stable/reference/visibility-and-privacy.html

Looks like they are supposed to be comment (`// ...`) and would need a mass update through out the whole repo.

**Comment by steveklabnik** [comment]
This is a rustdoc feature where things get hidden; I'm not sure why they're not hidden here though.

**Comment by steveklabnik** [comment]
Ah! Looks like this is a bug that was fixed, see beta: https://doc.rust-lang.org/beta/reference/visibility-and-privacy.html

Thanks for reporting, but looks like it's already taken care of 👍
