### ISSUE TITLE
Document `unrestricted_attribute_tokens`

### ISSUE THREAD

**Issue by ehuss** [rust-lang-nursery/reference#525]
- Version: 1.34
- Stabilization: https://github.com/rust-lang/rust/pull/57367
- Tracking: https://github.com/rust-lang/rust/issues/55208

**Comment by flying-sheep** [comment]
An aspect that hasn’t become clear to me: Are macros expanded or is macro syntax simply passed to on?

**Comment by petrochenkov** [comment]
@flying-sheep 
Macro invocations are simply passed on, exactly like with proc macros.

Proc macros will need some mechanism like https://github.com/rust-lang/rfcs/pull/2320 to interpret macro invocations in both their input and their helper attributes.
