### ISSUE TITLE
Scala as an influence for Traits

### ISSUE THREAD

**Issue by jeffvandyke** [rust-lang-nursery/reference#557]
I like the [influences section](https://doc.rust-lang.org/reference/influences.html) because it acknowledges work done in other languages and shows Rust as not being an alien language. When I started learning traits, the first thing I thought of was Scala and how traits can extend other traits using a concept of mixins when used for a class ([Scala Traits docs](https://docs.scala-lang.org/tour/traits.html), [Mixins docs](https://docs.scala-lang.org/tour/mixin-class-composition.html)) I don't know about Rust's design history, but is that fair to put in that section as an inspiration for traits?

**Comment by Centril** [comment]
I don't think so. While `trait` in Rust has the same keyword as in Scala, and both achieve ad-hoc polymorphism, it is not the same concept. For example, Scala's traits give rise to subtyping as in Java's `interface`s but in Rust this is not the case. Moreover, Scala's traits are not coherent and violate canonicity ("global uniqueness of implementations") but this is a key aspect of Rust's traits.

The direct influence for Rust's traits are Haskell's type classes and I think it would be misleading to point to Scala as an influence.

**Comment by Centril** [comment]
The influences section probably needs a do-over however. More influences could be mentioned and some dropped.

**Comment by jeffvandyke** [comment]
Sounds good, thanks for feedback!
