### ISSUE TITLE
Request: Give usage examples for the `ignore` attribute

### ISSUE THREAD

**Issue by Phrohdoh** [rust-lang-nursery/reference#561]
_Originally filed at https://github.com/rust-lang/book/issues/1911_

---

https://doc.rust-lang.org/reference/attributes.html#testing makes mention of the `ignore` attribute but does not tell the reader how to use it.

> A function annotated with the test attribute can also be annotated with the `ignore` attribute. The `ignore` attribute tells the test harness to not execute that function as a test. It will still only be compiled when compiling with the test harness.

**Comment by ehuss** [comment]
There is an example in the latest version:
https://doc.rust-lang.org/nightly/reference/attributes/testing.html#the-ignore-attribute
Is that good enough?

**Comment by Phrohdoh** [comment]
Oh, so there is!

That looks great, thanks!
