### ISSUE TITLE
Include a formal specification of the language

### ISSUE THREAD

**Issue by DemiMarie** [rust-lang-nursery/reference#608]
It would be desirable to have a formal specification of Rust.  This has several benefits:

* It allows for formal reasoning about, and verification of, Rust programs and tools.
* It removes ambiguity in the specification

Writing such a specification is likely very difficult, but it would be nice to do at some point.

**Comment by steveklabnik** [comment]
This is what the reference is intended to eventually be; there's no reason to have an issue to track it. Thank you!
