### ISSUE TITLE
Document precedence of `:`

### ISSUE THREAD

**Issue by czipperz** [rust-lang-nursery/reference#618]
https://doc.rust-lang.org/nightly/reference/expressions.html#expression-precedence is missing the colon operator `:`.  In [previous versions](https://doc.rust-lang.org/1.23.0/reference/expressions.html#expression-precedence) it was the same precedence as `as`.

**Comment by Centril** [comment]
Type ascription is not currently stable.

**Comment by czipperz** [comment]
KK.  Thanks
