### ISSUE TITLE
Unmatched dilimiters in type_length_limit example

### ISSUE THREAD

**Issue by adamAndMath** [rust-lang-nursery/reference#649]
The example code for [type_length_limit](https://doc.rust-lang.org/reference/attributes/limits.html#the-recursion_limit-attribute) has the following lines.
```rust
// `f::<(i32, i32, i32, i32, i32, i32, i32, i32, i32)>>` requires more
```
```rust
f(((1, 2, 3, 4, 5, 6, 7, 8, 9));
```
They should be
```rust
// `f::<(i32, i32, i32, i32, i32, i32, i32, i32, i32)>` requires more
```
```rust
f((1, 2, 3, 4, 5, 6, 7, 8, 9));
```

**Comment by ehuss** [comment]
Thanks, this has already been fixed via #621.  The latest version can be seen by adding `nightly` in the url: https://doc.rust-lang.org/nightly/reference/attributes/limits.html#the-type_length_limit-attribute
