### ISSUE TITLE
What is the correct desugaring for index expressions? 

### ISSUE THREAD

**Issue by OnlyLys** [rust-lang-nursery/reference#651]
The reference seems to contradict the standard library documentation on this point.

Currently the [reference](https://doc.rust-lang.org/reference/expressions/array-expr.html?highlight=index#array-and-slice-indexing-expressions) states that `a[b]` is equivalent to `*std::ops::Index::index(&a, b)` while the [standard library documentation](https://doc.rust-lang.org/std/ops/trait.Index.html) states that it should instead be `*a.index(b)`. Clearly these two are not the same since the latter will allow auto-borrow / auto-dereferencing for `a`. 

Just testing with some code it appears that the behavior is more like the latter:

```
let v: &&Vec<i32> = &&vec![1, 2, 3];

// Compiler complains that `Index` has not been implemented for &&Vec<i32>
let a: i32 = *std::ops::Index::index(&v, 1);

// OK due to method lookup being able to find the implementation for Vec<i32>
use std::ops::Index;
let b: i32 = *v.index(1);

// This works. So it appears that the correct desugaring is to *v.index(1) 
let c: i32 = v[1];
```

**Comment by ehuss** [comment]
Doesn't the sentence immediately after in the reference state that?

> Just as with methods, Rust will also insert dereference operations on `a` repeatedly to find an implementation.

I would say the std docs are a little off, since it is ambiguous about method resolution.

**Comment by OnlyLys** [comment]
Wow! Somehow I had a monumental lapse in attention and missed the line that immediately follows. 

> Just as with methods, Rust will also insert dereference operations on a repeatedly to find an implementation.

Thank you for the response. I'll be closing this now. 😅
