### ISSUE TITLE
Oxford comma usage is inconsistent

### ISSUE THREAD

**Issue by Havvy** [rust-lang-nursery/reference#664]
In PR #663, @hawkinsw stated that the comma usage is inconsistent.

I don't know which sites are missing commas, but they should be added where missing. @hawkinsw: Can you point out those locations?

**Comment by hawkinsw** [comment]
I will start a list and build a PR from there, if that's ok? It might not
be too many, but I swear I saw at least one when I was looking through the
reference. I hope I didn't alarm anyone with that comment. I didn't mean to!

**Comment by Havvy** [comment]
I'm not alarmed. If it happens, it happens. It's just nice to get it fixed when it's spotted.
