### ISSUE TITLE
Hide warning about incompleteness

### ISSUE THREAD

**Issue by kpp** [rust-lang-nursery/reference#681]
The red banner with "For now, this reference is a best-effort document..." scares me a lot. Would you please add a button "I got it" which hides the banner and sets a cookie that prevents its popup again?

**Comment by ehuss** [comment]
I would personally like to just remove it.  Or just have it on the front page.  @Havvy @Centril do you have an opinion?  I added a github link in the upper-right corner of every page, if people want an easy way to file issues.

**Comment by Centril** [comment]
The warning seems useless atm -- maybe we should exchange it for "this document is not normative".

**Comment by ehuss** [comment]
The front page already says "Finally, this book is not normative." and includes a big red box that it is incomplete, and emphasizes that it is informal.  I don't think it needs shouting on every page.

**Comment by Centril** [comment]
Oh; that banner. Sure, yeah, let's remove it.
