### ISSUE TITLE
Document the types of "static" functions

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang-nursery/reference#72]
refiling https://github.com/rust-lang/rust/issues/38211

There are a few aspects of "static" (non-closure) functions that I find useful to know but I can't seem to locate in the docs:
* They all implement `Copy`.
    * And they don't implement `Clone` (is this unusual?)
* They automatically implement the respective function call traits `Fn`, `FnMut` and `FnOnce`.
    * And since they don't have an environment... they are equivalent?

I think it might be appropriate to have an entry in the `std`/`core` documentation with this. Not sure if a new "primitive" page would be appropriate for it.

**Comment by Havvy** [comment]
The proper section is [function-item-types](https://doc.rust-lang.org/nightly/reference/types.html#function-item-types).

They all do implement Clone now.
