### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by durka** [rust-lang-nursery/reference#73]
A great strength of the old one-page reference was that you could search it. Full text search would be great. See also https://github.com/azerupi/mdBook/issues/51.

**Comment by steveklabnik** [comment]
Agreed, but as you noted, this is blocked on that upstream.

Until then, you can click the print button and control-f it to get the older behavior.

**Comment by oberien** [comment]
With rust-lang-nursery/mdbook#604 merged and rust-lang-nursery/mdbook#51 closed, should this be reopened until the new search from mdbook is available in the reference?
