### ISSUE TITLE
Add bors/homu/bors-ng mergebot?

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang-nursery/reference#8]
Plans to add a mergebot for this repo? I've been pretty satisfied with https://bors-ng.github.io/, though I understand if we just want to use the same homu instance in charge of rust-lang/rust

**Comment by steveklabnik** [comment]
I am not sure. I think that it's not as useful for smaller repos, personally. I've already disabled force pushing and required review.

I'm not opposed. Let's leave this open and see how it goes.

**Comment by frewsxcv** [comment]
As @Havvy mentioned on IRC, not much value in keeping this open at this point
