### ISSUE TITLE
Broken links in macros chapter

### ISSUE THREAD

**Issue by kw217** [rust-lang-nursery/reference#82]
The page https://doc.rust-lang.org/reference/macros.html contains links to "Macros" and "Procedural Macros". Presumably these should point to the subsections immediately below it in the reference - "Macros By Example" and "Procedural Macros". But instead they are old links to the Book, which go to the "The Rust Programming Language Has Moved" page. The only way to navigate to the intended subsections is to notice them in the navigation sidebar and click on them there.

It would be good to fix these links to go to the right place.

**Comment by Havvy** [comment]
This should have been closed as fixed on Aug 31.

**Comment by kw217** [comment]
This still looks wrong to me. Clicking on the links on the page takes me to the "There is a new edition of the book" page, and I need one more click to get to the right subsection.

**Comment by steveklabnik** [comment]
@kw217 it just hasn't hit stable yet; on beta, it is fixed. Next release of rust will contain the fix.
