### ISSUE TITLE
talk about the additional flags to the #[doc] attribute

### ISSUE THREAD

**Issue by QuietMisdreavus** [rust-lang-nursery/reference#92]
Some comments in IRC today brought to my attention that you can add to the stock attributes that are pasted into doctests. They extrapolated from [these lines in libstd](https://github.com/rust-lang/rust/blob/e326e86b47edcded3313944a81f126a633032d86/src/libstd/lib.rs#L221-L222) and were able to add `#![doc(test(attr(deny(warnings))))]` to their own crate to add a `#![deny(warnings)]` to all their doctests. It would be nice to investigate how rustdoc handles these extensions to the doc attribute and add it to the line about it in the Attributes chapter.

**Comment by lukaramu** [comment]
I guess that should then also be documented in the [Rustdoc book](https://github.com/rust-lang/rust/blob/master/src/doc/rustdoc/src/SUMMARY.md)?
