### ISSUE TITLE
v2 Book says Cargo generates main.rs automagically, it does not

### ISSUE THREAD

**Issue by jamisonbryant** [rust-lang-nursery/reference#93]
**This is not a Cargo issue. Cargo is working fine.** This is a description of a discrepancy that I have found between Cargo's behavior and the v2 Book.

In section 1.2 the book says:

> _Cargo has generated a "Hello World!" for you, just like the one we wrote earlier! So that part is the same._

However, running the command `cargo new <crate_name>` to create a new Cargo project does not, in fact, generate this "Hello World" file. It instead generates a `lib.rs` that does not compile to an executable, but rather to a variety of library resource files. To clarify:

* **Expected (according to docs):** Cargo generates a main.rs containing Hello World code
* **Actual:** Cargo generates a lib.rs with no "concrete" code at all
* **Resolution:** Update the docs to indicate that Cargo will not, in fact, generate this file

**Comment by jamisonbryant** [comment]
Updated title to better reflect that the issue is with the Book and not with Cargo

**Comment by jamisonbryant** [comment]
Never mind. I did not run the `cargo new` command with the `--bin` switch, thus the crate was not created as a binary project, so no `main.rs` was generated.

**Comment by teq0** [comment]
Wait, this is still an issue. The book doesn't say to use the --bin flag, so following the book to the letter doesn't work as expected. The book still needs to be updated. The docs Getting Started section is correct though.
